### PR TITLE
Change variants folder T-Beam (espressif#4496)

### PR DESCRIPTION
**Pull request by meehow**

### CODE REVIEW

**Comment by geeksville** [comment]
ooh @meehow OOOH that sounds great.  Just  question though - as your were fixing did you figure out why this change was needed now? (i.e. it has been this way for a long time - so I'm puzzled as to why the build is suddently failing now)

**Comment by geeksville** [comment]
fix for https://github.com/meshtastic/Meshtastic-device/issues/753 (just to keep github crosslinking)

**Comment by meehow** [comment]
Author of the commit pointed to https://github.com/espressif/arduino-esp32/pull/4212/commits/914a50f51e0ad9afa1e7c26618b6f02bf6dfc8d5 , but I dodn't dive into this topic, just wanted to compile it and noticed that this simple change can fix the build. It's bit weird because 914a50f51e0ad9afa1e7c26618b6f02bf6dfc8d5 is not included to meshtastic master branch.

**Comment by geeksville** [comment]
hmm thanks - yeah I'm puzzled also but your fix is right ;-)

**Comment by geeksville** [comment]
also someday we really neeed to update wrt master again ;-)

**Pull request merged**
